name: GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          node-version: '16.14'
      - run: npx pnpm install
      - run: npx pnpm lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          node-version: '16.14'
      - run: npx pnpm install
      - run: npx pnpm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          node-version: '16.14'
      - run: npx pnpm install
      - run: npx pnpm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.14'
          registry-url: https://registry.npmjs.org/
      - run: echo "C'est ici que l'on déploiera"

